services:
  smartroute:
    container_name: smartroute_back
    build: .
    expose:
      - "8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=True
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - smartroute
    networks:
      - app-network

networks:
  app-network:
    driver: bridge