services:
  smartroute:
    container_name: smartroute_back
    build: ./backend
    expose:
      - "8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=False
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - smartroute
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge